title: SwiftUI Styling Approaches
description: From "Big Head" to "Long Tail"
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
highlighter: rouge
